# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-04 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juan', '0002_auto_20180501_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='course1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=15)),
                ('mode', models.CharField(max_length=15)),
                ('salary', models.IntegerField(null=True)),
                ('avgTariff', models.FloatField(null=True)),
                ('minTariff', models.FloatField(null=True)),
                ('employment', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
