# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-04 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juan', '0003_auto_20180504_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course1',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
