# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-05 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juan', '0004_auto_20180504_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course1',
            name='url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course1',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
