# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('typeC', models.CharField(max_length=10)),
                ('salary', models.IntegerField(null=True)),
                ('tariff', models.IntegerField(null=True)),
            ],
        ),
    ]
